### ISSUE TITLE
AngularD3CloudModule' does not appear to be an NgModule class.(-996002)

### ISSUE THREAD

**Issue by SandraMThomas** [maitrungduc1410/d3-cloud-angular#10]
AngularD3CloudModule' does not appear to be an NgModule class.(-996002)
angular-d3-cloud.module.d.ts(1, 22): This likely means that the library (angular-d3-cloud) which declares AngularD3CloudModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by sliceoflif3** [comment]
I also ran into the same issue.

**Comment by maitrungduc1410** [comment]
Which angular version are you using?

**Comment by sliceoflif3** [comment]
Angular CLI: 16.1.0
Node: 16.20.1
Package Manager: npm 8.19.4
OS: win32 x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1601.0 (cli-only)
@angular-devkit/core         16.1.0 (cli-only)
@angular-devkit/schematics   16.1.0 (cli-only)
@schematics/angular          16.1.0 (cli-only)

**Comment by maitrungduc1410** [comment]
okay, I'll check and get back to you

**Comment by maitrungduc1410** [comment]
@sliceoflif3  I fixed this issue, please upgrade to v2.0.3
